spring.application.name=delivery-workers
server.port=8091
camunda.bpm.client.base-url=http://localhost:8080/engine-rest
camunda.bpm.client.worker-id=delivery-workers
camunda.bpm.client.async-response-timeout=10000